eureka:
  client:
    serviceUrl:
      defaultZone: http://site.localhost.com:8080/eureka/

info:
  app:
    name: Client-${server.port}
    description: This is a book service
    version: 1.0.0


endpoints:
  shutdown:
    enabled: true