spring: 
 mvc: 
  view: 
   prefix: /WEB-INF/jsp/
   suffix: .jsp

github:
 client: 
  clientId: xxxxxxxxxx
  clientSecret: xxxxxxxxxx
  accessTokenUri: https://github.com/login/oauth/access_token
  userAuthorizationUri: https://github.com/login/oauth/authorize
  clientAuthenticationScheme: form
 resource: 
  userInfoUri: https://api.github.com/user
  
stack:
 client: 
  clientId: 7392
  clientSecret: pb*inWwwI2Lgg8NoRGnjvQ((
  accessTokenUri: https://stackexchange.com/oauth/access_token
  userAuthorizationUri: https://stackexchange.com/oauth
  clientAuthenticationScheme: form
 resource: 
  userInfoUri: https://api.stackexchange.com/2.2/me