spring: 
 mvc: 
  view: 
   prefix: /WEB-INF/jsp/
   suffix: .jsp

github:
 client: 
  clientId: 4ccc59906a14649ddce9
  clientSecret: 037fb80179d4e16f6e5a596f0eddb2962dc1f93d
  accessTokenUri: https://github.com/login/oauth/access_token
  userAuthorizationUri: https://github.com/login/oauth/authorize
  clientAuthenticationScheme: form
 resource: 
  userInfoUri: https://api.github.com/user

google:
 client: 
  clientId: 965602360467-pna0jah5b4smfm5h3hb4opcnsr0jsapv.apps.googleusercontent.com
  clientSecret: BMIBA_55NjUjWactwuEvQrkE
  accessTokenUri: https://www.googleapis.com/oauth2/v4/token
  userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
  clientAuthenticationScheme: query
  scope: profile
 resource: 
  userInfoUri: https://www.googleapis.com/plus/v1/people/me
  preferTokenInfo: false